# Gradle Properties
org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false

# Source Options
use_modern_java_syntax = false

# Compilation Options
generate_sources_jar = true
generate_javadocs_jar = false

# Testing
enable_junit_testing = false
show_testing_output = false

# Mod Information
mod_version = 1.0.0
version = 1.0.0
root_package = com.mysticalchemy
mod_id = mysticalchemy
mod_name = Mystic Alchemy Legacy
mod_jar_name = MysticAlchemyLegacy-1.12.2

# Mod Metadata (Optional)
mod_description = Expands potions and brewing in the game to be more dynamic and magical.
mod_url = https://github.com/Mithion/Mystic-Alchemy
mod_update_json =
mod_authors = Mithion, WinDanesz (port author)
mod_credits = Original mod by Mithion. 1.12.2 port by WinDanesz.
mod_logo_path =
mod_license = All Rights Reserved

# Mapping Properties
mapping_channel = stable
mapping_version = 39
use_dependency_at_files = true

# Run Configurations
minecraft_username = WinDanesz
extra_jvm_args =
extra_tweak_classes =

# Maven Publishing
publish_to_maven = false
publish_to_local_maven = false
maven_name = ${mod_name}
maven_url =

# Publishing
release_type = alpha
publish_with_changelog = ${{ it.file('CHANGELOG.md').exists() }}

# Publishing to CurseForge
publish_to_curseforge = false
curseforge_project_id =
curseforge_debug = false

# Publishing to Modrinth
publish_to_modrinth = false
modrinth_project_id =
modrinth_sync_readme = false
modrinth_debug = false

# Modify Minecraft Sources
change_minecraft_sources = false

# Tags
use_tags = false
tag_class_name = ${root_package}.Tags

# Access Transformers
use_access_transformer = false
access_transformer_locations = ${mod_id}_at.cfg

# Mixins
use_mixins = false
mixin_booter_version = 10.2
generate_mixins_json = false
mixin_configs = ${mod_id}
mixin_refmap = mixins.${mod_id}.refmap.json
mixin_package = ${root_package}.mixin

# Coremods
is_coremod = false
coremod_includes_mod = true
coremod_plugin_class_name =

# AssetMover
use_asset_mover = false
asset_mover_version = 2.5